name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Hugging Face Space
        uses: huggingface/space-deploy-action@v1
        with:
          repo_id: https://huggingface.co/spaces/airworkx/vertexchat  # Full URL
          branch: main
          build_script: 'python app.py'
